version: '3.9'

services:
  rss-proxy-utf8:
    image: rss-proxy-utf8
    build:
      context: .
    container_name: rss-proxy-utf8
    ports:
      - "9090:8080"  # Map port 9090 on the host to 8080 in the container
    volumes:
      - ./data:/app/data  # Bind the local `data` folder to `/app/data` in the container
